phrase:
  #access_token: ACCESS_TOKEN
  project_id: 43f1dd1ee0c0b4e79379cd1d268138b8
  file_format: xml
  push:
    sources:
      - file: ./app/src/main/res/values/strings.xml
        params:
          file_format: xml
          locale_id: en
          tags: github
          update_translations: true
          unescape_linebreaks: true
#          autotranslate: true
      - file: ./app/src/main/res/values-ja/strings.xml
        params:
          file_format: xml
          locale_id: ja
          tags: github
          update_translations: true
          unescape_linebreaks: true
      - file: ./app/src/main/res/values-zh-rCN/strings.xml
        params:
          file_format: xml
          locale_id: zh-CN
          tags: github
          update_translations: true
          unescape_linebreaks: true
  pull:
    targets:
      - file: ./app/src/main/res/values-ja/strings.xml
        params:
          file_format: xml
          locale_id: ja
          tags: github
      - file: ./app/src/main/res/values-fr/strings.xml
        params:
          file_format: xml
          locale_id: fr
          tags: github
      - file: ./app/src/main/res/values-zh-rTW/strings.xml
        params:
          file_format: xml
          locale_id: zh-TW
          tags: github
